services:
  backend:
    build: .
    command: ${DJANGO_RUN_COMMAND}
    ports:
      - '8080:8080'
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .env.local
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always

  celery:
    build: .
    command: celery -A moving worker -l info
    env_file:
      - .env.local
    depends_on:
      - postgres
      - redis
    restart: always

volumes:
  postgres_data: