# Generated by Django 4.0.4 on 2025-04-03 01:41

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('floor', models.IntegerField()),
                ('zip_code', models.CharField(max_length=20)),
                ('has_elevator', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CA')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('moving_date', models.DateTimeField()),
                ('promocode', models.CharField(blank=True, max_length=55, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='New', max_length=255)),
                ('order_type', models.CharField(choices=[('Moving', 'Moving'), ('Delivery', 'Delivery')], max_length=255)),
                ('apartment_type', models.CharField(blank=True, choices=[('Studio', 'Studio'), ('1 Bedroom', '1 Bedroom'), ('2 Bedroom', '2 Bedroom'), ('3 Bedroom', '3 Bedroom'), ('4 Bedroom', '4 Bedroom'), ('Multilevel Condo - Up to 750 sqft', 'Multilevel Condo - Up to 750 sqft'), ('Multilevel Condo - Up to 1000 sqft', 'Multilevel Condo - Up to 1000 sqft'), ('Multilevel Condo - Up to 1250 sqft', 'Multilevel Condo - Up to 1250 sqft'), ('Multilevel Condo - Up to 1500 sqft', 'Multilevel Condo - Up to 1500 sqft'), ('Multilevel Condo - Up to 2000 sqft', 'Multilevel Condo - Up to 2000 sqft'), ('House - Up to 1000 sqft', 'House - Up to 1000 sqft'), ('House - Up to 1500 sqft', 'House - Up to 1500 sqft'), ('House - Up to 2000 sqft', 'House - Up to 2000 sqft'), ('House - Up to 2500 sqft', 'House - Up to 2500 sqft'), ('House - Up to 3000 sqft', 'House - Up to 3000 sqft'), ('Office - Up to 750 sqft', 'Office - Up to 750 sqft'), ('Office - Up to 1000 sqft', 'Office - Up to 1000 sqft'), ('Office - Up to 1500 sqft', 'Office - Up to 1500 sqft'), ('Office - Up to 2000 sqft', 'Office - Up to 2000 sqft'), ('Office - Up to 2500 sqft', 'Office - Up to 2500 sqft'), ('Office - Up to 3000 sqft', 'Office - Up to 3000 sqft')], max_length=255, null=True)),
                ('large_items', models.IntegerField(blank=True, null=True)),
                ('medium_items', models.IntegerField(blank=True, null=True)),
                ('end_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_address', to='base.address')),
                ('start_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_address', to='base.address')),
            ],
        ),
    ]
